---
- meta: end_play
  when: (ansible_distribution != "CentOS" and ansible_distribution_major_version != "7")

- name: install pacemaker packages
  yum:
    name:
      - pacemaker
      - pcs
      - psmisc
      - policycoreutils-python
      - libselinux-python
      - mc
      - corosync-qdevice

- name: Change the hostname to our standard
  hostname:
    name: "{{ inventory_hostname }}"

- name: "Build hosts file"
  lineinfile:
   path:   /etc/cloud/templates/hosts.redhat.tmpl
   line:   "{{ hostvars[item].ansible_subnet1 }} {{ item }}"
   insertbefore: "{{ item }}"
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['web_pcm'] }}"

- name: start pcsd service
  systemd:
      name: pcsd
      state: started
      enabled: yes

- name: restart machine
  reboot:

- name: Enable clustered locking for LVM
  command: lvmconf --enable-cluster
  notify: "start lvm2-lvmetad"

- name: Set password for local hacluster user
  user:
   name: "{{ cluster_user }}"
   password: "{{ pcm_password | password_hash('sha512') }}"
   state: present
   update_password: always
   create_home: yes
  notify: "restart pcsd"
  no_log: true

- name: pcs auth
  shell: |
         pcs cluster auth {{ groups['web_pcm']|join(' ') }} -u {{ cluster_user }} -p {{ pcm_password }}
         pcs cluster setup --name {{ cluster_name }} {{ groups['web_pcm']|join(' ') }} --force
         pcs cluster enable --all
         pcs cluster start --all
  ignore_errors: true