---
- name: stop nginx
  service:
    name: nginx
    state: stopped

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted

- name: reload php-fpm
  service:
    name: php-fpm
    state: reloaded
    enabled: yes