---
- name: Create DLM and CLVM
  shell: |
      pcs property set stonith-enabled=false
      pcs property set no-quorum-policy=ignore
      pcs resource create dlm systemd:dlm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
      pcs resource create clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
      pcs constraint order start dlm-clone then clvmd-clone

- name: Create FS
  shell: echo y | pvcreate /dev/mapper/mpath* -ff

- name: Check pv
  shell: pvs

- name: vgcreate
  shell: vgcreate -Ay -cy cluster_vg /dev/mapper/mpath*

- name: lvcreate
  shell: lvcreate -L1800M -n cluster_lv cluster_vg

- name: mkfs.gfs2
  shell: echo y | sudo mkfs.gfs2 -O -j3 -p lock_dlm -t ha_cluster:gfs2 /dev/cluster_vg/cluster_lv

- name: create clusterfs
  command: pcs resource create clusterfs Filesystem device="/dev/cluster_vg/cluster_lv" directory="/mnt/gfs2" fstype="gfs2" "options=noatime" op monitor interval=10s on-fail=ignore clone interleave=true

- name: constraint order
  command: pcs constraint order start clvmd-clone then clusterfs-clone

- name: colocation
  command: pcs constraint colocation add clusterfs-clone with clvmd-clone