---
- meta: end_play
  when: (ansible_distribution != "CentOS" and ansible_distribution_major_version != "7")

- yum:
    name:
      - epel-release
      - zip
      - unzip
      - bzip2
      - wget
      - libselinux-python
      - policycoreutils-python
      - git
      - curl
      - mc
    state: present

- name: Change the hostname to our standard
  hostname:
      name: "{{ inventory_hostname }}"
  when:
      ansible_fqdn != ansible_host

- name: Build hosts file
  blockinfile:
      dest: /etc/cloud/templates/hosts.redhat.tmpl
      content: "{{ lookup('template', 'templates_etc_hosts.j2') }}"
      state: present
