---
# handlers file for ansible-pacemaker
#- name: pacemaker commit ###commented out for now...broken in ansible 2.0
#  pacemaker: commit

- name: restart corosync
  service:
    name: corosync
    state: restarted
  become: true

- name: restart pacemaker
  service:
    name: pacemaker
    sleep: 10
    state: restarted
  become: true

- name: Enables corosync at boot
  copy:
    dest: /etc/default/corosync
    content: "START=yes"

- name: Registers pacemaker service
  service:
    name: pacemaker
    enabled: true

- name: restart pcsd
  systemd:
    name: pcsd.service
    state: restarted

- name: start lvm2-lvmetad
  systemd:
    name: lvm2-lvmetad.service
    state: stopped
