---
- meta: end_play
  when: (ansible_distribution != "CentOS" and ansible_distribution_major_version != "7")

- name: install NTPD
  yum:
    name: ntp
    state: present
  notify:
    - ntp running

- name: dis cronyd
  yum:
    name: cronyd
    state: absent

- name: set timezone
  command: timedatectl set-timezone Europe/Minsk